//! The stylesheets and script, compiled into the binary.
//!
//! Topcoat's own asset pipeline writes a directory next to the executable and
//! reads it at startup, so shipping meant handing over two things and keeping
//! them together. These files are small and never change without a rebuild —
//! the grid's two come from `fu_gantt_web`, the rest are the pages' own — so
//! they can simply live inside it: one file to copy, and `cargo
//! run` works without the dev CLI having staged a bundle first.
//!
//! Each is served under a URL carrying a hash of its own bytes, so the
//! immutable caching is honest — a new build is a new URL.

use std::sync::LazyLock;

use fu_gantt_web::{GRID_CSS, GRID_JS, fingerprint};
use topcoat::{
    Result,
    context::Cx,
    router::{Body, Response, raw_path_params, route},
};

/// Tailwind's output, generated by `build.rs` into `OUT_DIR`.
const TAILWIND: &str = include_str!(concat!(env!("OUT_DIR"), "/tailwind.css"));

/// Dark mode and the colour tokens the pages read. Hand-written. It also ties
/// the grid's `--fg-*` properties to those tokens, which is how the grid takes
/// this program's colours.
const THEME_CSS: &str = include_str!("../assets/theme.css");
const FAVICON: &str = include_str!("../assets/favicon.svg");
const PAGE_JS: &str = include_str!("../assets/page.js");

struct StaticFile {
    name: &'static str,
    body: &'static str,
    content_type: &'static str,
}

const FILES: [StaticFile; 6] = [
    StaticFile {
        name: "theme.css",
        body: THEME_CSS,
        content_type: "text/css; charset=utf-8",
    },
    StaticFile {
        name: "tailwind.css",
        body: TAILWIND,
        content_type: "text/css; charset=utf-8",
    },
    StaticFile {
        name: "grid.css",
        body: GRID_CSS,
        content_type: "text/css; charset=utf-8",
    },
    StaticFile {
        name: "grid.js",
        body: GRID_JS,
        content_type: "text/javascript; charset=utf-8",
    },
    StaticFile {
        name: "favicon.svg",
        body: FAVICON,
        content_type: "image/svg+xml",
    },
    StaticFile {
        name: "page.js",
        body: PAGE_JS,
        content_type: "text/javascript; charset=utf-8",
    },
];

/// `/static/<hash>/<name>` for each file, worked out once on first use.
static URLS: LazyLock<Vec<String>> = LazyLock::new(|| {
    FILES
        .iter()
        .map(|file| format!("/static/{}/{}", fingerprint(file.body), file.name))
        .collect()
});

pub fn theme_css() -> &'static str {
    &URLS[0]
}

pub fn tailwind_css() -> &'static str {
    &URLS[1]
}

pub fn grid_css() -> &'static str {
    &URLS[2]
}

pub fn grid_js() -> &'static str {
    &URLS[3]
}

pub fn favicon() -> &'static str {
    &URLS[4]
}

/// The server-drawn pages' few behaviours: asking before a destructive button,
/// and going back from the error page.
pub fn page_js() -> &'static str {
    &URLS[5]
}

#[route(GET "/static/{hash}/{name}")]
async fn serve(cx: &Cx) -> Result<Response> {
    let name = raw_path_params(cx)
        .iter()
        .find(|(key, _)| *key == "name")
        .map(|(_, value)| value);

    let Some(file) = FILES.iter().find(|file| Some(file.name) == name) else {
        return Ok(Response::builder()
            .status(404)
            .body(Body::from("not found"))?);
    };

    Ok(Response::builder()
        .header("Content-Type", file.content_type)
        // The hash is in the path, so this URL's bytes can never change.
        .header("Cache-Control", "public, max-age=31536000, immutable")
        .body(Body::from(file.body))?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_file_made_it_into_the_binary() {
        for file in &FILES {
            assert!(!file.body.is_empty(), "{} が空", file.name);
        }

        assert!(
            GRID_JS.contains("fugantt-grid"),
            "グリッドの JS が入っていない"
        );
        assert!(TAILWIND.len() > 1000, "Tailwind の CSS が小さすぎる");
    }

    /// A changed file must not keep the old URL, or browsers will hold the old
    /// bytes for a year.
    #[test]
    fn the_url_moves_with_the_contents() {
        assert!(grid_js().starts_with("/static/"));
    }
}
