//! The stylesheets and script, compiled into the binary.
//!
//! Topcoat's own asset pipeline writes a directory next to the executable and
//! reads it at startup, so shipping meant handing over two things and keeping
//! them together. These three files are small and never change without a
//! rebuild, so they can simply live inside it: one file to copy, and `cargo
//! run` works without the dev CLI having staged a bundle first.
//!
//! Each is served under a URL carrying a hash of its own bytes, so the
//! immutable caching is honest — a new build is a new URL.

use std::sync::LazyLock;

use topcoat::{
    Result,
    context::Cx,
    router::{Body, Response, raw_path_params, route},
};

/// Tailwind's output, generated by `build.rs` into `OUT_DIR`.
const TAILWIND: &str = include_str!(concat!(env!("OUT_DIR"), "/tailwind.css"));

/// The grid island, built by `npm run build` in `web/` and committed.
const GRID_CSS: &str = include_str!("../web/dist/grid.css");
const GRID_JS: &str = include_str!("../web/dist/grid.js");
const FAVICON: &str = include_str!("../web/dist/favicon.svg");

struct StaticFile {
    name: &'static str,
    body: &'static str,
    content_type: &'static str,
}

const FILES: [StaticFile; 4] = [
    StaticFile {
        name: "tailwind.css",
        body: TAILWIND,
        content_type: "text/css; charset=utf-8",
    },
    StaticFile {
        name: "grid.css",
        body: GRID_CSS,
        content_type: "text/css; charset=utf-8",
    },
    StaticFile {
        name: "grid.js",
        body: GRID_JS,
        content_type: "text/javascript; charset=utf-8",
    },
    StaticFile {
        name: "favicon.svg",
        body: FAVICON,
        content_type: "image/svg+xml",
    },
];

/// `/static/<hash>/<name>` for each file, worked out once on first use.
static URLS: LazyLock<Vec<String>> = LazyLock::new(|| {
    FILES
        .iter()
        .map(|file| format!("/static/{}/{}", fingerprint(file.body), file.name))
        .collect()
});

pub fn tailwind_css() -> &'static str {
    &URLS[0]
}

pub fn grid_css() -> &'static str {
    &URLS[1]
}

pub fn grid_js() -> &'static str {
    &URLS[2]
}

pub fn favicon() -> &'static str {
    &URLS[3]
}

/// A short digest of the contents, so a changed file gets a changed URL.
///
/// FNV-1a rather than a cryptographic hash: nothing here is a secret, and the
/// only job is to differ when the bytes differ.
fn fingerprint(body: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;

    for byte in body.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }

    format!("{hash:016x}")
}

#[route(GET "/static/{hash}/{name}")]
async fn serve(cx: &Cx) -> Result<Response> {
    let name = raw_path_params(cx)
        .iter()
        .find(|(key, _)| *key == "name")
        .map(|(_, value)| value);

    let Some(file) = FILES.iter().find(|file| Some(file.name) == name) else {
        return Ok(Response::builder()
            .status(404)
            .body(Body::from("not found"))?);
    };

    Ok(Response::builder()
        .header("Content-Type", file.content_type)
        // The hash is in the path, so this URL's bytes can never change.
        .header("Cache-Control", "public, max-age=31536000, immutable")
        .body(Body::from(file.body))?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_file_made_it_into_the_binary() {
        for file in &FILES {
            assert!(!file.body.is_empty(), "{} が空", file.name);
        }

        assert!(GRID_JS.contains("fugantt-grid"), "グリッドの JS が入っていない");
        assert!(TAILWIND.len() > 1000, "Tailwind の CSS が小さすぎる");
    }

    /// A changed file must not keep the old URL, or browsers will hold the old
    /// bytes for a year.
    #[test]
    fn the_url_moves_with_the_contents() {
        assert_ne!(fingerprint("a"), fingerprint("b"));
        assert_eq!(fingerprint(GRID_JS), fingerprint(GRID_JS));
        assert!(grid_js().starts_with("/static/"));
    }
}
